name: Busted

on: [push, pull_request]

jobs:
  busted:
    name: busted
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.1
      - name: Setup Lua Rocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup dependencies
        run: luarocks install busted && luarocks install luassert
      - name: Run Tests
        run: make test