name: Luacheck

on: [push, pull_request]

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.1
      - name: Setup Lua Rocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup dependencies
        run: luarocks install luacheck
      - name: Run Code Linter
        run: make lint